"""add question type to interview questions

Revision ID: bfb0ad94fc4e
Revises: b16be4404a6a
Create Date: 2026-07-31 10:17:02.280779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb0ad94fc4e'
down_revision: Union[str, Sequence[str], None] = 'b16be4404a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "interview_questions",
        sa.Column(
            "question_type",
            sa.String(length=50),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE interview_questions
        SET question_type = category
        WHERE question_type IS NULL
        """
    )

    op.alter_column(
        "interview_questions",
        "question_type",
        existing_type=sa.String(length=50),
        nullable=False,
    )   


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_questions', 'question_type')
    # ### end Alembic commands ###
